export const SHOW_RESULT_MILLISECONDS = 10000

export const TOTAL_POLLING_INTERVAL_MILLISECONDS = 1900

export const TOTAL_COUNTDOWN_MILLISECONDS = 3000
export const COUNTDOWN_INTERVAL_MILLISECONDS = 1000
